### ISSUE TITLE
individual installation of plugins

### ISSUE THREAD

**Issue by NumerousHats** [noahgh221/archivesspace-duke-plugins#1]
Are there dependencies among these plugins that require them all to be installed simultaneously, or can one be installed by itself? In particular, does aspace-search-identifier have dependencies? I attempted to install it on ASpace 1.5.4 but it doesn't seem to be working: I see "plugins/aspace-search-identifier/frontend/views/search/_listing.html.erb" being rendered in the log file, but no identifiers are appearing in either accession or resource listings.

Thanks in advance!

**Comment by noahgh221** [comment]
I don't think there are any dependencies with the aspace-search-identifier plugin.  I have not tested this plugin with version 1.5.4, so perhaps the plugin isn't compatible with that version.  

I believe Lyrasis wrote this plugin, and they've made a few edits to it since I copied it.  You might try this version: https://github.com/lyrasis/aspace-search-identifier

Also, just to clarify, this plugin only affects search results, not browse results.  If you want to add the identifier column to the browse screens, you can do that by editing preferences directly in the staff interface.

**Comment by NumerousHats** [comment]
Thanks for the info. Much appreciated!
